#%RAML 1.0 Library
usage: Library of DataTypes
types:
  Error: !include /exchange_modules/4f17708b-9c6d-4000-b1b2-4ab6b9446262/error/1.0.0/error.raml
  Hotel: !include ../datatypes/Hotel.raml
  Registration: !include ../datatypes/Registration.raml
  Booking: !include ../datatypes/Booking.raml
  Status: !include ../datatypes/Status.raml  